-- 코드를 작성해주세요

WITH T1 AS (SELECT FI.*,FNI.FISH_NAME FROM FISH_INFO AS FI
LEFT JOIN FISH_NAME_INFO AS FNI
ON FI.FISH_TYPE = FNI.FISH_TYPE),
T2 AS(SELECT FISH_TYPE,MAX(LENGTH) AS MAX_LENGTH FROM T1
          GROUP BY FISH_TYPE)

SELECT T1.ID, T1.FISH_NAME, T1.LENGTH
FROM T1
JOIN T2
ON T1.FISH_TYPE = T2.FISH_TYPE AND T1.LENGTH = T2.MAX_LENGTH
ORDER BY T1.ID ASC;
