-- 코드를 입력하세요
SELECT B.CATEGORY AS CATEGORY, SUM(BS.SALES) AS TOTAL_SALES FROM BOOK_SALES AS BS
LEFT JOIN BOOK AS B
ON BS.BOOK_ID=B.BOOK_ID
WHERE BS.SALES_DATE LIKE '2022-01%'
GROUP BY CATEGORY
ORDER BY CATEGORY ASC